# Generated by Django 5.2.4 on 2025-07-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0002_accident_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='image',
        ),
        migrations.AddField(
            model_name='accident',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
