# Generated by Django 5.2.4 on 2025-07-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0003_remove_accident_image_accident_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='cover_image',
        ),
    ]
